package hibernateClases2;
// Generated 17 dic 2024, 17:16:18 by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Camisetas generated by hbm2java
 */
public class Camisetas implements java.io.Serializable {

	private int codigocamiseta;
	private String tipo;
	private String color;
	private float importepremio;
	private Set resumenCamisetases = new HashSet(0);
	private Set llevas = new HashSet(0);

	public Camisetas() {
	}

	public Camisetas(int codigocamiseta, String tipo, String color, float importepremio) {
		this.codigocamiseta = codigocamiseta;
		this.tipo = tipo;
		this.color = color;
		this.importepremio = importepremio;
	}

	public Camisetas(int codigocamiseta, String tipo, String color, float importepremio, Set resumenCamisetases,
			Set llevas) {
		this.codigocamiseta = codigocamiseta;
		this.tipo = tipo;
		this.color = color;
		this.importepremio = importepremio;
		this.resumenCamisetases = resumenCamisetases;
		this.llevas = llevas;
	}

	public int getCodigocamiseta() {
		return this.codigocamiseta;
	}

	public void setCodigocamiseta(int codigocamiseta) {
		this.codigocamiseta = codigocamiseta;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public float getImportepremio() {
		return this.importepremio;
	}

	public void setImportepremio(float importepremio) {
		this.importepremio = importepremio;
	}

	public Set getResumenCamisetases() {
		return this.resumenCamisetases;
	}

	public void setResumenCamisetases(Set resumenCamisetases) {
		this.resumenCamisetases = resumenCamisetases;
	}

	public Set getLlevas() {
		return this.llevas;
	}

	public void setLlevas(Set llevas) {
		this.llevas = llevas;
	}

}
