package hibernateClases2;
// Generated 17 dic 2024, 17:16:18 by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ciclistas generated by hbm2java
 */
public class Ciclistas implements java.io.Serializable {

	private int codigociclista;
	private Ciclistas ciclistas;
	private Equipos equipos;
	private String nombreciclista;
	private Date fechanacimiento;
	private float peso;
	private Set resumenCamisetases = new HashSet(0);
	private Set llevas = new HashSet(0);
	private Set ciclistases = new HashSet(0);
	private Set tramospuertoses = new HashSet(0);
	private Set etapases = new HashSet(0);

	public Ciclistas() {
	}

	public Ciclistas(int codigociclista, Equipos equipos, String nombreciclista, Date fechanacimiento, float peso) {
		this.codigociclista = codigociclista;
		this.equipos = equipos;
		this.nombreciclista = nombreciclista;
		this.fechanacimiento = fechanacimiento;
		this.peso = peso;
	}

	public Ciclistas(int codigociclista, Ciclistas ciclistas, Equipos equipos, String nombreciclista,
			Date fechanacimiento, float peso, Set resumenCamisetases, Set llevas, Set ciclistases, Set tramospuertoses,
			Set etapases) {
		this.codigociclista = codigociclista;
		this.ciclistas = ciclistas;
		this.equipos = equipos;
		this.nombreciclista = nombreciclista;
		this.fechanacimiento = fechanacimiento;
		this.peso = peso;
		this.resumenCamisetases = resumenCamisetases;
		this.llevas = llevas;
		this.ciclistases = ciclistases;
		this.tramospuertoses = tramospuertoses;
		this.etapases = etapases;
	}

	public int getCodigociclista() {
		return this.codigociclista;
	}

	public void setCodigociclista(int codigociclista) {
		this.codigociclista = codigociclista;
	}

	public Ciclistas getCiclistas() {
		return this.ciclistas;
	}

	public void setCiclistas(Ciclistas ciclistas) {
		this.ciclistas = ciclistas;
	}

	public Equipos getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Equipos equipos) {
		this.equipos = equipos;
	}

	public String getNombreciclista() {
		return this.nombreciclista;
	}

	public void setNombreciclista(String nombreciclista) {
		this.nombreciclista = nombreciclista;
	}

	public Date getFechanacimiento() {
		return this.fechanacimiento;
	}

	public void setFechanacimiento(Date fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	public float getPeso() {
		return this.peso;
	}

	public void setPeso(float peso) {
		this.peso = peso;
	}

	public Set getResumenCamisetases() {
		return this.resumenCamisetases;
	}

	public void setResumenCamisetases(Set resumenCamisetases) {
		this.resumenCamisetases = resumenCamisetases;
	}

	public Set getLlevas() {
		return this.llevas;
	}

	public void setLlevas(Set llevas) {
		this.llevas = llevas;
	}

	public Set getCiclistases() {
		return this.ciclistases;
	}

	public void setCiclistases(Set ciclistases) {
		this.ciclistases = ciclistases;
	}

	public Set getTramospuertoses() {
		return this.tramospuertoses;
	}

	public void setTramospuertoses(Set tramospuertoses) {
		this.tramospuertoses = tramospuertoses;
	}

	public Set getEtapases() {
		return this.etapases;
	}

	public void setEtapases(Set etapases) {
		this.etapases = etapases;
	}

}
