package hibernateClases2;
// Generated 17 dic 2024, 17:16:18 by Hibernate Tools 5.6.15.Final

/**
 * ResumenCamisetasId generated by hbm2java
 */
public class ResumenCamisetasId implements java.io.Serializable {

	private int codigoequipo;
	private int codigociclista;
	private int codigocamiseta;

	public ResumenCamisetasId() {
	}

	public ResumenCamisetasId(int codigoequipo, int codigociclista, int codigocamiseta) {
		this.codigoequipo = codigoequipo;
		this.codigociclista = codigociclista;
		this.codigocamiseta = codigocamiseta;
	}

	public int getCodigoequipo() {
		return this.codigoequipo;
	}

	public void setCodigoequipo(int codigoequipo) {
		this.codigoequipo = codigoequipo;
	}

	public int getCodigociclista() {
		return this.codigociclista;
	}

	public void setCodigociclista(int codigociclista) {
		this.codigociclista = codigociclista;
	}

	public int getCodigocamiseta() {
		return this.codigocamiseta;
	}

	public void setCodigocamiseta(int codigocamiseta) {
		this.codigocamiseta = codigocamiseta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResumenCamisetasId))
			return false;
		ResumenCamisetasId castOther = (ResumenCamisetasId) other;

		return (this.getCodigoequipo() == castOther.getCodigoequipo())
				&& (this.getCodigociclista() == castOther.getCodigociclista())
				&& (this.getCodigocamiseta() == castOther.getCodigocamiseta());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoequipo();
		result = 37 * result + this.getCodigociclista();
		result = 37 * result + this.getCodigocamiseta();
		return result;
	}

}
