package hibernateClases2;
// Generated 17 dic 2024, 17:16:18 by Hibernate Tools 5.6.15.Final

/**
 * ResumenCamisetas generated by hbm2java
 */
public class ResumenCamisetas implements java.io.Serializable {

	private ResumenCamisetasId id;
	private Camisetas camisetas;
	private Ciclistas ciclistas;
	private Equipos equipos;
	private int numveces;
	private float importepremio;

	public ResumenCamisetas() {
	}

	public ResumenCamisetas(ResumenCamisetasId id, Camisetas camisetas, Ciclistas ciclistas, Equipos equipos,
			int numveces, float importepremio) {
		this.id = id;
		this.camisetas = camisetas;
		this.ciclistas = ciclistas;
		this.equipos = equipos;
		this.numveces = numveces;
		this.importepremio = importepremio;
	}

	public ResumenCamisetasId getId() {
		return this.id;
	}

	public void setId(ResumenCamisetasId id) {
		this.id = id;
	}

	public Camisetas getCamisetas() {
		return this.camisetas;
	}

	public void setCamisetas(Camisetas camisetas) {
		this.camisetas = camisetas;
	}

	public Ciclistas getCiclistas() {
		return this.ciclistas;
	}

	public void setCiclistas(Ciclistas ciclistas) {
		this.ciclistas = ciclistas;
	}

	public Equipos getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Equipos equipos) {
		this.equipos = equipos;
	}

	public int getNumveces() {
		return this.numveces;
	}

	public void setNumveces(int numveces) {
		this.numveces = numveces;
	}

	public float getImportepremio() {
		return this.importepremio;
	}

	public void setImportepremio(float importepremio) {
		this.importepremio = importepremio;
	}

}
